### ISSUE TITLE
Error in GUI ver 0.11

### ISSUE THREAD

**Issue by moieric11** [dutu/poloLender#100]
Version:
Restarted:
NaN undefined NaN, NaN:NaN AM (Invalid date)
Poloniex API activity:

The GUI show me NaN instead of the hour and date of restart

**Comment by xR2** [comment]
I might be wrong but... this seems to happen due to poloniex timeout, so the bot doesn't get the information.

**Comment by dutu** [comment]
Thanks. the display issue error occurs when the browser hasn't been updated from the lending engine.
This is fixed (nothing will be displayed instead of NaN) in the new version that will release soon.

**Comment by dutu** [comment]
Fixed in version 1.0.0

**Comment by ZerglingGo** [comment]
This issue still have a problem. Please check this.

![chrome_2017-07-14_01-39-41](https://user-images.githubusercontent.com/3365053/28177329-6d4889b2-6835-11e7-8596-3db14f2ca634.png)

**Comment by moieric11** [comment]
Have you updated to last version ?

**Comment by ZerglingGo** [comment]
Yes. I updated latest version.

**Comment by dutu** [comment]
@ZerglingGo you are not on the last version, which is 1.0.0.
Last version has the "settings" tab. Your Screenshot doesn't have it.

**Comment by ZerglingGo** [comment]
Hmm. That's weird.
I had update 1.0.0 and checked version finally. and cleaning cache too.

Now it is working. I think this is temporary problems.

Thank you.
